# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0002_auto_20171016_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.SmallIntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('carrera', models.CharField(max_length=30)),
            ],
        ),
    ]
