# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0005_asistencia_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
