# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0007_auto_20171101_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='idAlumno',
            new_name='idalumno',
        ),
    ]
