# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0008_auto_20171104_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idA', models.IntegerField()),
                ('idD', models.IntegerField()),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='asistencia',
        ),
        migrations.AddField(
            model_name='date',
            name='idgroup',
            field=models.IntegerField(null=True),
        ),
    ]
