# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0009_auto_20171104_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCalif', models.IntegerField()),
                ('idAlumno', models.IntegerField()),
                ('calif', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='calificacionAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial', models.IntegerField()),
                ('idGrupo', models.IntegerField()),
            ],
        ),
    ]
