# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0011_grupo_numexamenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='metricasGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGrupo', models.SmallIntegerField()),
                ('num_exam', models.SmallIntegerField()),
                ('num_proy', models.SmallIntegerField()),
                ('num_retardos', models.SmallIntegerField()),
                ('exam_avg', models.FloatField()),
                ('proyect_avg', models.FloatField()),
                ('atten_avg', models.FloatField()),
                ('part_avg', models.FloatField()),
                ('tareas_avg', models.FloatField()),
            ],
        ),
    ]
