# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0013_calificacionalumnoproject_calificacionproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('date', models.CharField(max_length=10)),
                ('idGrupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='worksCalif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idWork', models.IntegerField()),
                ('idAlumno', models.IntegerField()),
                ('calif', models.CharField(max_length=2)),
            ],
        ),
    ]
