# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0014_works_workscalif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='numExamenes',
        ),
    ]
